# Generated by Django 3.2.9 on 2021-11-15 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('m_name', models.CharField(max_length=20, null=True)),
                ('l_name', models.CharField(max_length=20)),
                ('passport', models.CharField(max_length=50, unique=True)),
                ('tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
                ('cost', models.IntegerField()),
                ('id_cases', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lawyer.casestype')),
                ('id_scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lawyer.scope')),
            ],
        ),
        migrations.CreateModel(
            name='Lawyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('m_name', models.CharField(max_length=20, null=True)),
                ('l_name', models.CharField(max_length=20)),
                ('free', models.BooleanField(default=False)),
                ('id_scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lawyer.scope')),
            ],
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lawyer.clients')),
                ('id_lawyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lawyer.lawyers')),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lawyer.services')),
            ],
        ),
    ]
