# Generated by Django 3.2.9 on 2021-11-15 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cases',
            options={'ordering': ['name'], 'verbose_name': 'Дело', 'verbose_name_plural': 'Дела'},
        ),
        migrations.AlterModelOptions(
            name='casestype',
            options={'ordering': ['id'], 'verbose_name': 'Тип дела', 'verbose_name_plural': 'Тип дела'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ['l_name'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='lawyers',
            options={'ordering': ['l_name'], 'verbose_name': 'Адвокат', 'verbose_name_plural': 'Адвокаты'},
        ),
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['id'], 'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['id'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='cases',
            name='content',
            field=models.TextField(blank=True, verbose_name='Материалы дела'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lawyer.clients', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='id_lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lawyer.lawyers', verbose_name='Адвокат'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='id_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lawyer.services', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='casestype',
            name='type',
            field=models.CharField(max_length=255, unique=True, verbose_name='Тип дела'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='f_name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='l_name',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='m_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='passport',
            field=models.CharField(max_length=50, unique=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='tel',
            field=models.IntegerField(verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='lawyers',
            name='f_name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='lawyers',
            name='free',
            field=models.BooleanField(default=False, verbose_name='Занятость'),
        ),
        migrations.AlterField(
            model_name='lawyers',
            name='id_scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lawyer.scope', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='lawyers',
            name='l_name',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='lawyers',
            name='m_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='type',
            field=models.CharField(max_length=255, unique=True, verbose_name='Cпециализация'),
        ),
        migrations.AlterField(
            model_name='services',
            name='cost',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='services',
            name='id_cases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lawyer.casestype', verbose_name='Дело'),
        ),
        migrations.AlterField(
            model_name='services',
            name='id_scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lawyer.scope', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='services',
            name='type',
            field=models.CharField(max_length=255, unique=True, verbose_name='Услуга'),
        ),
    ]
