# Generated by Django 3.2.9 on 2021-11-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0003_alter_services_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='id_cases',
        ),
        migrations.RemoveField(
            model_name='services',
            name='id_scope',
        ),
    ]
