# Generated by Django 3.2.9 on 2021-11-16 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0004_auto_20211116_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='id_case_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='lawyer.casestype', verbose_name='Тип дела'),
            preserve_default=False,
        ),
    ]
