# Generated by Django 3.2.9 on 2021-11-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0005_cases_id_case_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата записи')),
                ('id_case_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lawyer.casestype', verbose_name='Тип дела')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lawyer.clients', verbose_name='Клиент')),
                ('id_lawyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lawyer.lawyers', verbose_name='Адвокат')),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lawyer.services', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрация',
                'ordering': ['date'],
            },
        ),
    ]
